server:
  port: 9000

spring:
  application:
    name: appBiblioteca

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sistema
    driver-class-name: org.postgresql.Driver

# Optional JPA properties
jpa:
  hibernate.ddl-auto: update
  show-sql: true

